mutation CreateUser($username: String!, $email: String!, $passwordHash: String!, $role: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it's for new user registration.") {
  user_insert(data: {username: $username, email: $email, passwordHash: $passwordHash, role: $role, createdAt_expr: "request.time"})
}

query GetMyProfile @auth(level: USER) {
  user(key: {id_expr: "auth.uid"}) {
    id
    username
    email
    displayName
    bio
    contactInfo
    createdAt
  }
}

mutation UpdateMyBio($bio: String!) @auth(level: USER) {
  user_update(key: {id_expr: "auth.uid"}, data: {bio: $bio})
}

query GetChatRoomMessages($chatRoomId: UUID!) @auth(level: USER) {
  chatMessages(where: {chatRoomId: {eq: $chatRoomId}}, orderBy: [{sentAt: ASC}]) {
    id
    messageContent
    sentAt
    sender {
      id
      username
      displayName
    }
  }
}