query ListAllResources @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it lists all available resources.") {
  resources {
    id
    name
    type
    address
    contactNumber
    websiteUrl
    description
    operatingHours
  }
}

mutation CreateNewPost($content: String!, $isPublic: Boolean!, $imageUrl: String) @auth(level: USER, insecureReason: "This operation allows logged-in users to create a post for themselves.") {
  post_insert(data: {
    content: $content,
    createdAt_expr: "request.time",
    isPublic: $isPublic,
    imageUrl: $imageUrl,
    authorId_expr: "auth.uid"
  })
}

query GetMyProgressLogs @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as it retrieves their own progress logs.") {
  progressLogs(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    logDate
    cravingsDescription
    triggerDescription
    positiveActivity
    notes
    createdAt
  }
}

mutation AddResourceToFavorites($resourceId: UUID!) @auth(level: USER, insecureReason: "This operation allows logged-in users to favorite a resource.") {
  favoriteResource_insert(data: {
    userId_expr: "auth.uid",
    resourceId: $resourceId
  })
}